### ISSUE TITLE
Project's name

### ISSUE THREAD

**Issue by gituliar** [gituliar/fuchsia#1]
I like @magv's proposition to name this project after Fuchs. While **fuchsify** is a great name for a command or routine, a better name for the project could be **fuchsia**, which is a flower named after Fuchs -- not a mathematician, but botanist. Moreover, a logo and color of the project follow immediately... What do you think?

**Comment by magv** [comment]
I like it. It does sound a bit unnatural for a software name, but considering the long tradition of dubiously named scientific libraries (LiteRed? ISOLDE? BradPitt, seriosly?), "fuchsia" is fine.

Note that in English 'fuchsia' is actually pronounced closer to 'fewsha', which kind of breaks any association with Fuchs. We could probably insist on the pronunciation 'fook-see-ya', but I don't know if anyone would care.

Also note that there's at least one project on GitHub named 'fuchsia' (in an unrelated field), and there are some companies using that name.

Anyway, here's [a fuchsia I made](http://i.imgur.com/Jy5HKLD.png).

**Comment by gituliar** [comment]
In spite of all the doubts "fuchsia" seems to be fine for all -- two -- of us. That is fine.

As for the logo. I like the direction you chose and I am sure you can do way better. Maybe that will be the next project at your drawing class. :)

For now, I close this issue untill we have better ideas.

**Comment by magv** [comment]
So, will you rename the whole thing (along with the repository URL)?

**Comment by gituliar** [comment]
I just renamed the URL. Feel free to rename things while working on the issue #4. Once you are done, I will rename remaining things.

**Comment by magv** [comment]
As of commit abc9dd1fe3f848237b093fe1dc5aec7f567854b4, the rename is complete.
