### ISSUE TITLE
'fuchsia' binary installed by pip doesn't work

### ISSUE THREAD

**Issue by magv** [gituliar/fuchsia#10]
```
$ sage -pip install fuchsia

$ sage -pip list | grep fuchsia
fuchsia (16.6.23)

$ ~/SageMath-7.1/local/bin/fuchsia
Traceback (most recent call last):
  File "~/SageMath-7.1/local/bin/fuchsia", line 9, in <module>
    load_entry_point('fuchsia==16.6.23', 'console_scripts', 'fuchsia')()
[...]
  File "~/SageMath-7.1/local/lib/python2.7/site-packages/sage/interfaces/maxima.py", line 537, in __init__
    raise RuntimeError('You must get the file local/bin/sage-maxima.lisp')
RuntimeError: You must get the file local/bin/sage-maxima.lisp
```

**Comment by magv** [comment]
PS. Why isn't the test suite included with pip install? We sort of need it, at the very least to let users detect broken Maxima versions.

**Comment by gituliar** [comment]
Let us start with RuntimeError. When `pip` generates `bin/fuchsia` it puts `#!<path-to-sage>/bin/python` as a first line. What we actually need is `#!<path-to-sage>/bin/sage` instead. I have no idea how to fix that for the moment, but I will keep that in mind.

As for tests and other files. From what I understand, for that we need to put all the files we want to be installed to `site-packages` to a separate directory, i.e. to ship a package instead a module, like docs, tests, examples, etc. Now, pip installs only `fuchsia.py` and `fuchsia.egg-info` and there is no way to install additional files. Inspect `site-packages` directory for more examples.

**Comment by magv** [comment]
Oleksandr, you need to upload a fixed version to PyPI, otherwise this error is still present.
