### ISSUE TITLE
can not factor epsilon

### ISSUE THREAD

**Issue by F-Feng** [gituliar/fuchsia#13]
Hi,

Could you give a check on this case?
(Please see the attached matrix file
[m.txt] (https://github.com/gituliar/fuchsia/files/1230040/m.txt)
)
the last message look like as follows:

[    4.9s]    -> factorize
[    6.1s]        found 100 equations with 16 unknowns
[    6.5s]   can not factor epsilon

Thanks very much!

**Comment by magv** [comment]
This is an interesting case (which I don't remember seeing the likes of). By the time factorization is reached, the matrix is reduced to something like this:
```
{{-8*eps/(x-1)+8*eps/x,0,0,0,0},{0,-4*eps/(x-1)+6*eps/x,0,0,0},{0,-1/36*(240*eps^3-236*eps^2+56*eps+1)/(eps^2*(x-1))+1/36*(112*eps^3-172*eps^2+88*eps-15)/(eps^2*x),1/4*eps/(x-1)-1/4*eps/x,-25/72*eps/(x-1)+289/72*eps/x,0},{0,1/2*(16*eps^3-20*eps^2+8*eps-1)/(eps^2*(x-1))-1/2*(16*eps^3-20*eps^2+8*eps-1)/(eps^2*x),9/2*eps/(x-1)-9/2*eps/x,-25/4*eps/(x-1)+33/4*eps/x,0},{(4*eps-1)/(2*x-1)-(4*eps-1)/x,-8*(4*eps-1)/(x-1)-4*(12*eps^2-4*eps+1)/(eps*(2*x-1))+4*(8*eps^2-6*eps+1)/(eps*x),-72*eps^3/((4*eps^2-4*eps+1)*(x-1))+18*(2*eps^3+eps^2)/((4*eps^2-4*eps+1)*(2*x-1)),100*eps^3/((4*eps^2-4*eps+1)*(x-1))-17*(2*eps^3+eps^2)/((4*eps^2-4*eps+1)*(2*x-1)),-4*eps/(2*x-1)+4*eps/x}}
```

This indeed looks like a fully normalized Fuchsian matrix, so no error so far. Next, `factorize` tries to find an x-independent transformation to turn this into epsilon-form, but finds none. I've looked into the generated equations a bit, and the conclusion seems correct: there is no constant transformation that can turn this matrix into epsilon-form. There's not much Fuchsia can do about that.

Now, the interesting question is: can there be a non-constant transformation that reduces this matrix? This unfortunately I don't know.

**Comment by F-Feng** [comment]
Thanks so much for looking into such a case!

I am going to do some try on the normalized Fuchisan result,
and maybe try the solution of DE directly from the pre-factorize matrix ...

Anyway, thanks so much again!

**Comment by gituliar** [comment]
@F-Feng, could you, please, shortly describe in a context of which problem have you obtained this matrix?

**Comment by F-Feng** [comment]
@gituliar, thanks, and sure. 
The matrix shows up when I try to solve some master integrals which comes from this paper: https://arxiv.org/abs/1708.01129, the master integrals are listed in Eq.(44) of that paper, and when I try to solve those master integrals by differential equation, I get the matrix I sent to you.

**Comment by gituliar** [comment]
@F-Feng, thank you for the details. As @magv mentioned, your example is quite interesting since we have not seen Fuchsia ever fail at the last step, though that is possible in principle (for more details see Section 6 in http://arxiv.org/abs/1411.0911v1). For the moment, the only explanation I have for such behavior, is that your 5x5 matrix is part of a non-homogeneous system, since in the paper you mentioned authors deal with 13 masters. Hence, I would suggest you to try a complete 13x13 matrix. I think that in this case chances that Fuchsia will find a proper transformation are much higher.

**Comment by F-Feng** [comment]
@gituliar Thanks very much for the suggestion, I will try the complete master integrals, and if I succeed, I will post the detailed information. Thanks again!
