### ISSUE TITLE
Barkatou examples from ISSAC'10

### ISSUE THREAD

**Issue by gituliar** [gituliar/fuchsia#6]
There are two matrices by MB which he presented at ISSAC'10 conference (slides are in `papers` dir) which he claims to be Moser-reducible, but Fuchsia says that they are not. Who is right here?

In any case, it would be nice to have more information printed when `--log debug` flag is given, so that users could have some idea of what is going on, e.g. like it is done within `normalize`.

**Comment by magv** [comment]
The slides only say that those matrices are Moser-reducible. This
is true. If you'll run fuchsia with debug logging, you'll see that
indeed multiple (Moser) reduction steps are performed for both of them.

What the slides don't say is whether or not those matrices
can be reduced to Fuchsian form. Our reducer says they cannot,
and I see no reason to disbelieve that.

Maybe it was the error message that confused you? Currently it
says "matrix is Moser-irreducible", where by "matrix" it doesn't
necessarily mean the original matrix, but rather the matrix
that was passed to the function that generated this error --
which happens to be the intermediate matrix, obtained after
multiple reduction steps. If this is confusing, I can work on
improving this error message.

**Comment by magv** [comment]
In the mean while, I suggest you axe the `test_bar_issac10_2_17` and `test_bar_issac10_2_19` tests. They will never succeed.

**Comment by gituliar** [comment]
It is clear now what happens. Yes, please, keep the user updated as algorithm proceeds and print some warnings if we can not achieve an expected goal. Like in this example, matrices can be reduced, but not to the Fuchsian form. It make sense for me to save the final matrix in this case and warn the user that matrix is not in Fuchsian form. BTW, MatrixMarket format defines comments, so it looks nice to put such a warning in the output file as well.

As for the mentioned matrices, I will keep them, but for testing if `fuchsify` actually decreased a Poincare rank.

**Comment by magv** [comment]
> It make sense for me to save the final matrix in this case and warn the user that matrix is not in Fuchsian form.

When `fuchsify` learns that a matrix can not be reduced to Fuchsian form, the matrix itself can still be Moser-reducible at multiple points -- so it's only half as reduced as it could be. If we'd just return the matrix as is at this point, what would user do with it now? How do we even document what we're returning?

If you'd like `fuchsify` to continue reducing until *all* points are Moser-irreducible -- this will require additional coding, and I still don't think this is useful: `fuchsify` only ever performs a weak form of reduction, and if a user wants to see his matrix reduced *as much as possible*, then *super-reduction* and not *Moser-reduction* should be used -- so, ISOLDE, not fuchsia.

I think sticking to the `fuchsify` returns a matrix in Fuchsian form or throws an exception is good API design. We could print the half-reduced matrix in debug output, if the user is curious to see it.

**Comment by gituliar** [comment]
> I think sticking to the "`fuchsify` returns a matrix in Fuchsian form or throws an exception" contract is good API design. We could print the half-reduced matrix in debug output, if the user is curious to see it.

Yes, that sounds good.
